baseURL = "https://tagesbonus.de"
languageCode = "de"
title = "Tagesbonus.de - Tägliche Freispiele und Münzen"

defaultContentLanguage = "de"
[languages]
  [languages.de]
    languageName = "Deutsch"
    dateFormat = "2. January 2006"

[taxonomies]
  tag = "tags"

[permalinks]
post = "/:slug/"

[params]
  description = "Entdecken Sie tägliche Freispiele, Münzen und Belohnungen für Ihre Lieblings-Slot-Spiele wie Coin Master, Piggy Go, Slotomania, House of Fun und Pop Slots auf Tagesbonus.de. Maximieren Sie Ihr Spielerlebnis mit unseren täglich aktualisierten Boni!"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "JSON"]

